{"name":"Execute some hook before scenario","id":"exceptions-in-cucumber-hooks-must-result-in-failed-scenario-execution;execute-some-hook-before-scenario","testSteps":[{"number":1,"description":"Given some scenario with some before hook","duration":3,"startTime":"2018-03-08T16:07:59.720+01:00[Europe/Vienna]","result":"IGNORED","precondition":false},{"number":2,"description":"When an exception happens during hook execution","duration":1,"startTime":"2018-03-08T16:07:59.725+01:00[Europe/Vienna]","result":"IGNORED","precondition":false},{"number":3,"description":"Then the steps should have status Ignored","duration":1,"startTime":"2018-03-08T16:07:59.726+01:00[Europe/Vienna]","result":"IGNORED","precondition":false},{"number":4,"description":"But the scenario should be reported as Failing","duration":0,"startTime":"2018-03-08T16:07:59.727+01:00[Europe/Vienna]","result":"IGNORED","precondition":false}],"userStory":{"id":"exceptions-in-cucumber-hooks-must-result-in-failed-scenario-execution","storyName":"Exceptions in cucumber hooks must result in failed scenario execution","path":"test.feature","type":"feature"},"featureTag":{"name":"Exceptions in cucumber hooks must result in failed scenario execution","type":"feature"},"title":"Execute some hook before scenario","tags":[{"name":"Bug","type":"tag"},{"name":"Exceptions in cucumber hooks must result in failed scenario execution","type":"feature"}],"startTime":"2018-03-08T16:07:59.556+01:00[Europe/Vienna]","duration":178,"testFailureCause":{"errorType":"java.lang.RuntimeException","message":"Oops! Some exception happened during hook execution!","stackTrace":[{"declaringClass":"steps.hooks.TestHooks","methodName":"setup","fileName":"TestHooks.java","lineNumber":11},{"declaringClass":"cucumber.runner.UnskipableStep","methodName":"executeStep","fileName":"UnskipableStep.java","lineNumber":22},{"declaringClass":"cucumber.runner.Runner","methodName":"runPickle","fileName":"Runner.java","lineNumber":80}]},"testFailureClassname":"java.lang.RuntimeException","testFailureMessage":"Oops! Some exception happened during hook execution!","testFailureSummary":"ERROR;java.lang.RuntimeException;Oops! Some exception happened during hook execution!;TestHooks.java","projectKey":"","annotatedResult":"ERROR","manual":false,"testSource":"Cucumber","result":"ERROR"}